### ISSUE TITLE
Running my own relaystats

### ISSUE THREAD

**Issue by Frituurpanda** [andyleap/relaystats#1]
Hi Andy, 

I was looking at running my own version of what you did on andyleap.net:20000.
When i run the relaystats main.go i get the following error message: 
`Error, cannot open db: open /opt/relaystats/relaystats.db: no such file or directory`

I think i'm missing the database at this point specified at this point: 
`db, err = bolt.Open("/opt/relaystats/relaystats.db", 0666, &bolt.Options{})
 if err != nil {
  log.Fatalf("Error, cannot open db: %s", err)
 }`

Could you please give some insight into how i would be able to run this application myself?

Kind regards,
Frituurpanda

**Comment by andyleap** [comment]
Its most likely you are missing the directory that is hardcoded in.  You could either change that hardcoded path, or create the directory.  The database will be created automatically.

**Comment by Frituurpanda** [comment]
Oh god yes, that was exactly the last thing i had to do. Thanks a lot!!

**Comment by andyleap** [comment]
Ok then, I'm gonna go ahead and close this now
